---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: mwrock/Windows2012R2
    os_type: windows
    shell_type: powershell
    driver:
      communicator: winrm
    transport:
      name: winrm
      username: vagrant
      password: vagrant

suites:
  - name: default
    run_list:
      - recipe[btc-infrastructure::couchdb]
    attributes:
      admin_users:
        - username: "admin_username"
          password: "admin_password"
