---
driver:
  name: vagrant
provisioner:
  name: chef_zero
platforms:
- name: mwrock/Windows2012R2
  os_type: windows
  shell_type: powershell
  driver:
    communicator: winrm
  transport:
    name: winrm
    username: vagrant
    password: vagrant

suites:
- name: default
  run_list:
    - recipe[btc_infrastructure::default]
    - recipe[btc_infrastructure::couchdb]
    - recipe[btc_infrastructure::couchdb_bootstrap]
  attributes:
    admin_users:
      - username: "admin_username"
        password: "admin_password"
- name: nodejs
  run_list:
    - recipe[btc_infrastructure::default]
    - recipe[btc_infrastructure::git]
    - recipe[btc_infrastructure::nodejs]
    - recipe[btc_infrastructure::nodejs_deploy]
  data_bags_path: "test/integration/data_bags"
  
