---
driver:
  name: vagrant
provisioner:
  name: chef_solo
platforms:
- name: mwrock/Windows2012R2
  os_type: windows
  shell_type: powershell
  driver:
    communicator: winrm
  transport:
    name: winrm
    username: vagrant
    password: vagrant

suites:
- name: default
  run_list:
    - recipe[btc-infrastructure::default]
    - recipe[btc-infrastructure::couchdb]
    - recipe[btc-infrastructure::couchdb_bootstrap]
  attributes:
    admin_users:
      - username: "admin_username"
        password: "admin_password"
- name: nodejs
  run_list:
    - recipe[btc-infrastructure::default]
    - recipe[btc-infrastructure::nodejs]
    - recipe[btc-infrastructure::nodejs_deploy]
  attributes:
    deploy:
      btc-app-server:
        application: btc-app-server
        deploy_to: es5\src\index.js
        scm:
          password: null
          repository: https://s3.amazonaws.com/btc-app-server/btc-app-server-latest.tgz
          revision: null
          scm_type: s3
        environment_variables:
          NODE_ENV: production
          SERVER_SECRET: secret
          SERVER_JWT_EXP: 20m
